const controllerSigns = [
    "If you don't Rock and Stone, you ain't comin' home!",
    "Rock on!",
    "Rock and Stone... Yeeaaahhh!",
    "Rock and Stone forever!",
    "ROCK... AND... STONE!",
    "Rock and Stone!",
    "For Rock and Stone!",
    "We are unbreakable!",
    "Rock and roll!",
    "Rock and roll and stone!",
    "That's it lads! Rock and Stone!",
    "Like that! Rock and Stone!",
    "Yeaahhh! Rock and Stone!",
    "None can stand before us!",
    "Rock solid!",
    "Stone and Rock! ...Oh, wait...",
    "Come on guys! Rock and Stone!",
    "If you don't Rock and Stone, you ain't comin' home!",
    "We fight for Rock and Stone!",
    "We rock!",
    "Rock and Stone everyone!",
    "Stone.",
    "Yeah, yeah, Rock and Stone.",
    "Rock and Stone in the Heart!",
    "For Teamwork!",
    "Did I hear a Rock and Stone?",
    "Rock and Stone!",
    "Rock and Stone, Brother!",
    "Rock and Stone to the Bone!",
    "For Karl!",
    "Leave No Dwarf Behind!",
    "By the Beard!",
    "I eat rock for breakfast!"
]


module.exports = {controllerSigns};
