const USERNAME = "EDIT";
const SINGLE_HARVESTER_ROOM_CONTROLLER_LEVEL = 4;
const MIN_STORAGE_ENERGY = 100000;
const STRUCTURE_REPAIR_THRESHOLD = 0.8
const TERMINAL_ENERGY_TRANSFER_THRESHOLD = 100000
const TARGET_TERMINAL_TRANSFER_ROOM = 'E41N15'


module.exports = {
    SINGLE_HARVESTER_ROOM_CONTROLLER_LEVEL,
    MIN_STORAGE_ENERGY,
    TERMINAL_ENERGY_TRANSFER_THRESHOLD,
    STRUCTURE_REPAIR_THRESHOLD,
    USERNAME,
    TARGET_TERMINAL_TRANSFER_ROOM
};
