const USERNAME = "EDIT";
const SINGLE_HARVESTER_ROOM_CONTROLLER_LEVEL = 4;
const MIN_STORAGE_ENERGY = 100000;
const STRUCTURE_REPAIR_THRESHOLD = 0.8


module.exports = {SINGLE_HARVESTER_ROOM_CONTROLLER_LEVEL, MIN_STORAGE_ENERGY, STRUCTURE_REPAIR_THRESHOLD, USERNAME};
